# Generated by Django 5.2.17 on 2026-10-01 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_owner_integrity_and_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_collation='und-x-icu', max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(db_collation='und-x-icu', max_length=100),
        ),
    ]
