# Generated by Django 5.2.17 on 2026-10-01 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECEITA', 'Receita'), ('DESPESA', 'Despesa')], max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('PIX', 'Pix'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('DEBITO', 'Débito'), ('BOLETO', 'Boleto'), ('OUTRO', 'Outro')], max_length=13)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.subcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user', 'transaction_date'], name='transaction_owner_date_live')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('type__in', ['RECEITA', 'DESPESA'])), name='transaction_valid_type'), models.CheckConstraint(condition=models.Q(('payment_method__in', ['PIX', 'DINHEIRO', 'TRANSFERENCIA', 'DEBITO', 'BOLETO', 'OUTRO'])), name='transaction_valid_method')],
            },
        ),
    ]
